[tool.poetry]
name = "say_hello"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.scripts]
say_hello = "say_hello:start"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
