FROM ubuntu:12.04
# debian:buster-slim

# RUN apt update \
#  && apt install -y --no-install-recommends \
#     ca-certificates \
#     curl \
#     lzma \
#     openssl \
#     sudo \
#     wget \
#     xz-utils \
#  && apt -y autoremove \
#  && apt -y clean \
#  && rm -rf /var/lib/apt/lists/*

